### ISSUE TITLE
Error "Path does not exits"

### ISSUE THREAD

**Issue by blackfootsep** [light2yellow/csgo-csmd#10]
Hi,

while running csmd I get following error massage:

`/usr/local/bin $ csgo-csmd
CS:GO Community Server Materials Downloader v0.2.0

Traceback (most recent call last):
  File "/usr/local/bin/csgo-csmd", line 280, in <module>
    csmd.parse_args(CSMD.setup_args().parse_args())
  File "/usr/local/bin/csgo-csmd", line 163, in parse_args
    VerifyCLASyntax.path(self.csgo_path)
  File "/usr/local/bin/csgo-csmd", line 59, in path
    .format(ANSIColors.red, ANSIColors.end))
argparse.ArgumentTypeError: Path does not exist.`

I changed the csgo path in the csmd file but still i get the same error message.

Thanks in advance,
blackfoot.

**Comment by Nisodemus** [comment]
When you say you changed the csmd file path, did you change it to the one in the error message (/usr/local/bin/csgo-csmd) or another one? 
What distro are you using?
What is the file tree to CSGO and can you show the changes you have made to the csmd.conf file?
Have you tried to force the correct path with the documented argument '--csgo-path'?
