### ISSUE TITLE
IndexError: Server IP not found

### ISSUE THREAD

**Issue by lbaldim** [light2yellow/csgo-csmd#12]
CS:GO Community Server Materials Downloader v0.2.0

Traceback (most recent call last):
  File "/usr/local/bin/csgo-csmd", line 281, in <module>
    csmd.parse_console_log()
  File "/usr/local/bin/csgo-csmd", line 190, in parse_console_log
    .format(ANSIColors.red, ANSIColors.end))
IndexError: Server IP not found

Please help!

**Comment by TheSIlentLink** [comment]
I get the same error. Maybe a csgo update changed something.

**Comment by ccxex29** [comment]
I get the same error.
Is there anything wrong with the procedure.
