### ISSUE TITLE
Urllib error 300

### ISSUE THREAD

**Issue by Lesquivemeau** [light2yellow/csgo-csmd#5]
Logs:
`CS:GO Community Server Materials Downloader v0.2.0

Server: 79.137.24.187:27900
Base URL: http://zrd.es/fastdl//

Requesting maps/am_crashz_dust_v6v1.bsp.bz2
Requesting maps/am_crashz_dust_v6v1.bsp
Requesting sound/player/spraycan_shake_spray.mp3.bz2
Traceback (most recent call last):
  File "./csgo-csmd", line 282, in <module>
    csmd.download_materials()
  File "./csgo-csmd", line 258, in download_materials
    HTPPErrorHandler(err).handle()
  File "./csgo-csmd", line 36, in handle
    raise self.error
  File "./csgo-csmd", line 251, in download_materials
    with request.urlopen(url) as response, \
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 300: Multiple Choices
`

**Comment by light2yellow** [comment]
Ah, I see. I have disabled music files, so I never encountered it. Will be fixed.
