### ISSUE TITLE
403 Forbidden error

### ISSUE THREAD

**Issue by jawkPT** [light2yellow/csgo-csmd#9]
I don't know why, I think I've done all steps but I receving this error when I run csgo-csmd in Console.

this is a full log:
CS:GO Community Server Materials Downloader v0.2.0

Server: 185.113.141.54:30008
Base URL: http://fastdownload.igamers.pt/185.113.141.54-30008/csgo/

Requesting maps/am_piramid32.bsp.bz2
```
Traceback (most recent call last):
  File "/usr/local/bin/csgo-csmd", line 282, in <module>
    csmd.download_materials()
  File "/usr/local/bin/csgo-csmd", line 258, in download_materials
    HTPPErrorHandler(err).handle()
  File "/usr/local/bin/csgo-csmd", line 36, in handle
    raise self.error
  File "/usr/local/bin/csgo-csmd", line 251, in download_materials
    with request.urlopen(url) as response, \
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by Ashleyz4** [comment]
I'm also having this issue. Quite annoying.

The reason I'm also getting this is because the python file can't be used with sudo, and the CSGO-Path is on another drive that it can't access. Kinda odd.

**Comment by BinaryJava** [comment]
Same issue for me and cs go is on the same disk
